In [ ]:
#DATA TYPES THAT ARE USING IN DATA TYPES MAJORLY

In [ ]:
#DATA TYPES

In [ ]:
# integer
a = 2

In [ ]:
b = "vamshi"

In [ ]:
type(b)

str

In [ ]:
type(a)

int

In [ ]:
A = 4

In [ ]:
type(A)

int

In [ ]:
#python is case sensitive
a = 100

In [ ]:
A

4

In [ ]:
a

100

In [ ]:
# float
b = 150.0

In [ ]:
type(b)

float

In [ ]:
# string
c = 'vamshi'

In [ ]:
type(c)

str

In [ ]:
# boolean
d = False

In [ ]:
type(d)

bool

In [ ]:
d = int(d)

In [ ]:
type(d)

int

In [ ]:
c = bool(c)

In [ ]:
type(c)

bool

In [ ]:
print(c)

True


In [ ]:
sales = 100

In [ ]:
type(sales)

int

In [ ]:
sales = float(sales)

In [ ]:
type(sales)

float

In [ ]:
print(sales)

100.0


In [ ]:
sales = int(sales)

In [ ]:
type(sales)

int

In [ ]:
#Lists
list = ['data','science','python',100]

In [ ]:
list[2]

'python'

In [ ]:
list[3] = 'vamshi'

In [ ]:
list

['data', 'science', 'python', 'vamshi']

In [ ]:
#tuples # immutable(not able to change any values)

In [ ]:
list = ('data','science','python')

In [ ]:
list[1] = 'vamshi'

TypeError: ignored

In [ ]:
# DICTIONARIES

In [ ]:
f = {'country':'India','year':'1999','state':'tamilnadu'}

In [ ]:
f['country']

'India'

In [ ]:
del f['country']

In [ ]:
f

{'state': 'tamilnadu', 'year': '1999'}

In [ ]:
type(f)

dict

In [ ]:
# Numpy arrays 

In [ ]:
import numpy as np

In [ ]:
vam = [1,2,3,4]

In [ ]:
array = np.array(vam)  # creating array

In [ ]:
array

array([1, 2, 3, 4])

In [ ]:
type(array)   # type of array

numpy.ndarray

In [ ]:
print(array)

[1 2 3 4]


In [ ]:
vam = [1,2,3,4]    # creating n dimensional array
sai = [5,6,7,8]

In [ ]:
arr = np.array([vam,sai])   # creating n dimensional array

In [ ]:
arr.shape

(2, 4)

In [ ]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr.reshape(4,2)     # re-shaping it into total multiple count is 8 like 4*2,2*4,1*8,8*1
          

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
# indexing

In [ ]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr[0:2,1:4]   # using index numbers calling rows and columns

array([[2, 3, 4],
       [6, 7, 8]])

In [ ]:
arr[0:2,2:4]

array([[3, 4],
       [7, 8]])

In [ ]:
arr = np.arange(0,10,step=2)    # using arange calling 0 to 10 no.s and using step function calling with 3 diff

In [ ]:
arr

array([0, 2, 4, 6, 8])

In [ ]:
# copy or broadcasting
arr[2:] = 100   # from 2nd index it was changing with value 100

In [ ]:
arr

array([  0,   2, 100, 100, 100])

In [ ]:
arr1 = arr

In [ ]:
arr1[2:] = 500     # all the values after index 1 changed into 500 in arr1

In [ ]:
arr1

array([  0,   2, 500, 500, 500])

In [ ]:
arr     # by updating arr1 the values in arr also changed to 500

array([  0,   2, 500, 500, 500])

In [ ]:
arr1 = arr.copy()     # by using copy function arr list does not changed 

In [ ]:
print(arr)
arr1[2:] = 1000
print(arr1)

[  0   2 500 500 500]
[   0    2 1000 1000 1000]


In [ ]:
val=2          # showing all the variables that are lessthan 2 usefull in EDA
arr<2      

array([ True, False, False, False, False])

In [ ]:
arr%2

array([0, 0, 0, 0, 0])

In [ ]:
arr*2

array([   0,    4, 1000, 1000, 1000])

In [ ]:
# random value functions

In [ ]:
np.random.rand(3,3)      # random values 

array([[0.98473171, 0.55934626, 0.91768824],
       [0.2522182 , 0.51619128, 0.82931751],
       [0.36947444, 0.78732602, 0.90879588]])

In [ ]:
np.random.rand(5,5)

array([[0.41112648, 0.81669973, 0.77754351, 0.03742448, 0.08999005],
       [0.53178364, 0.39977271, 0.60020444, 0.91022919, 0.36032961],
       [0.4611331 , 0.4773147 , 0.59056841, 0.48777574, 0.99144451],
       [0.99412   , 0.66857106, 0.74834179, 0.16876878, 0.93247617],
       [0.38795061, 0.65725141, 0.54840477, 0.17102437, 0.21270482]])

In [ ]:
np.ones((2,5),dtype=int)      # givins all ones as outpt we can also change dtype

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.ones((1,4))

array([[1., 1., 1., 1.]])

In [ ]:
np.random.randint(0,100,10,dtype=int)

array([11, 50, 30, 46, 48,  5, 19, 83, 12,  6])

In [ ]:
np.random.randint(0,100,10,dtype=int).reshape(5,2)
                                              

array([[58, 47],
       [47, 82],
       [54, 94],
       [32, 18],
       [53, 23]])

In [ ]:
np.random.random_sample((1,5))

array([[0.93920041, 0.19076401, 0.76534123, 0.54325434, 0.86350556]])

In [ ]:
np.random.random_sample((1,5))

array([[0.73956765, 0.80925427, 0.36846023, 0.51446638, 0.65963814]])

In [ ]:
# Basic pandas

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame(np.arange(0,10).reshape(5,2),index=['Row1','Row2','Row3','Row4','Row5'],columns = ['col1','col2'])

In [ ]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','3','4','5'],columns=["Column1","Column2","3","4"])

In [ ]:
df

Column1  Column2   3   4
Row1        0        1   2   3
Row2        4        5   6   7
3           8        9  10  11
4          12       13  14  15
5          16       17  18  19

In [ ]:
df

col1  col2
Row1     0     1
Row2     2     3
Row3     4     5
Row4     6     7
Row5     8     9

In [ ]:
df.loc['Row1']

col1    0
col2    1
Name: Row1, dtype: int64

In [ ]:
type(df.loc['Row1'])   # having only one single row or one single col can be call as pandas series

pandas.core.series.Series

In [ ]:
type(df["col1"])

pandas.core.series.Series

In [ ]:
df.iloc[:4,:1]

col1
Row1     0
Row2     2
Row3     4
Row4     6

In [ ]:
df.iloc[:4,:2].values.shape   # converting dataftrame into array 

(4, 2)

In [ ]:
# Functions

In [ ]:
n = 24

if n%2==0:
  print('even no.s')

even no.s


In [ ]:

def even_odd(num):

 if num%2==0:
  print('it is even no.')
 else:
  print('it is odd no.') 


In [ ]:
even_odd(15)  

it is odd no.


In [ ]:
def add_nos(arg1,arg2):
  return arg1+arg2

val=add_nos(12,13)

In [ ]:
val

25

In [ ]:
def arguemnts(*args,**kwargs):
  print(args)
  print(kwargs)
arguemnts()  

In [ ]:
arguemnts('vamshi','thota',dob=1997,age=23)

('vamshi', 'thota')
{'dob': 1997, 'age': 23}


In [ ]:
# Lamda functions

In [ ]:
addition = lambda x,y,z:x+y+z
addition(2,3,4)

9

In [ ]:
addition = lambda a,b:a+b
addition(12,14)

26

In [ ]:
def even(num):
  if num%2==0:
    return True
even(6)  

True

In [ ]:
even = lambda a:a%2==0

In [ ]:
even(13)

False

In [ ]:
# list comprehension  in functions

In [ ]:
# list can be write by two ways 
# 1. list=[]
# 2. by list keyword    lst =list()

In [ ]:
lst = [1,2,3,4,5,6]

In [ ]:
new_lst=[]

for i in lst:
   new_lst.append(i)

In [ ]:
print(new_lst)

[1, 2, 3, 4, 5, 6]


In [ ]:
new_lst

[1, 2, 3, 4, 5, 6]

In [ ]:
[i for i in lst]

[1, 2, 3, 4, 5, 6]

In [ ]:
new_lst=[]
for i in lst:
  if i%3==0:              # by writing these many lines of code
    new_lst.append(i)
print(new_lst)

[3, 6]


In [ ]:
[i for i in lst if i%2==0]       # by single line of code

[2, 4, 6]

In [ ]:
# map functions in python

In [ ]:
def even_odd(num):
  if num%2==0:
    return "number {} is even".format(num)
  else:  
    return "number {} is odd".format(num)

In [ ]:
def even_odd():
  if num%2==0:
    return num
  else:
    return num  

In [ ]:
even_odd()

NameError: ignored

In [ ]:
def even_odd(num):
  if num%2==0:
      return 'all even {} numbers'.format(num)
  else:
     return 'all odd {} numbers'.format(num)    


In [ ]:
even_odd(4)

'all even 4 numbers'

In [ ]:
lst = [1,24,33,23,22,64,47,54,89,78]

In [ ]:
def even_odd(num):
  if num%2==0:
    return True
  else:
    return False

In [ ]:
even_odd(16)

True

In [ ]:
list(map(even_odd,lst))

TypeError: ignored

In [ ]:
lst = [1,24,33,23,22,64,47,54,89,78]

In [ ]:
list(map(even_odd,lst))

TypeError: ignored

In [ ]:
# Filters in functions

In [ ]:
def even(num):
  if num%2==0:
    return True

In [ ]:
even(4)

True

In [ ]:
lst = [1,24,33,23,22,64,47,54,89,78]

In [ ]:
list(filter(even,lst))

TypeError: ignored

In [ ]:
list(filter(lambda num:num%2==0,lst))

TypeError: ignored

In [ ]:
# Decorators

In [ ]:
a = [1,2,3,4]
for i in a:
  if i%2==0:
    print(i)

2
4
